# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\crearParametro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CrearParametro(object):
    def setupUi(self, CrearParametro):
        CrearParametro.setObjectName("CrearParametro")
        CrearParametro.resize(381, 281)
        self.cancelar = QtWidgets.QPushButton(CrearParametro)
        self.cancelar.setGeometry(QtCore.QRect(222, 230, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelar.setFont(font)
        self.cancelar.setObjectName("cancelar")
        self.crear = QtWidgets.QPushButton(CrearParametro)
        self.crear.setGeometry(QtCore.QRect(50, 230, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.crear.setFont(font)
        self.crear.setObjectName("crear")
        self.label_2 = QtWidgets.QLabel(CrearParametro)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(CrearParametro)
        self.label_3.setGeometry(QtCore.QRect(50, 150, 61, 20))
        self.label_3.setObjectName("label_3")
        self.tipo = QtWidgets.QComboBox(CrearParametro)
        self.tipo.setGeometry(QtCore.QRect(170, 150, 161, 21))
        self.tipo.setObjectName("tipo")
        self.tipo.addItem("")
        self.tipo.addItem("")
        self.tipo.addItem("")
        self.tipo.addItem("")
        self.label_91 = QtWidgets.QLabel(CrearParametro)
        self.label_91.setGeometry(QtCore.QRect(30, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.nombre = QtWidgets.QLineEdit(CrearParametro)
        self.nombre.setGeometry(QtCore.QRect(170, 90, 161, 21))
        self.nombre.setText("")
        self.nombre.setObjectName("nombre")

        self.retranslateUi(CrearParametro)
        QtCore.QMetaObject.connectSlotsByName(CrearParametro)

    def retranslateUi(self, CrearParametro):
        _translate = QtCore.QCoreApplication.translate
        CrearParametro.setWindowTitle(_translate("CrearParametro", "Dialog"))
        self.cancelar.setText(_translate("CrearParametro", "Cancelar"))
        self.crear.setText(_translate("CrearParametro", "Crear"))
        self.label_2.setText(_translate("CrearParametro", "Nombre "))
        self.label_3.setText(_translate("CrearParametro", "Tipo"))
        self.tipo.setItemText(0, _translate("CrearParametro", "Entero"))
        self.tipo.setItemText(1, _translate("CrearParametro", "Real"))
        self.tipo.setItemText(2, _translate("CrearParametro", "Texto"))
        self.tipo.setItemText(3, _translate("CrearParametro", "Boolean"))
        self.label_91.setText(_translate("CrearParametro", "Crear Nuevo Parametro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CrearParametro = QtWidgets.QDialog()
    ui = Ui_CrearParametro()
    ui.setupUi(CrearParametro)
    CrearParametro.show()
    sys.exit(app.exec_())
