# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\eliminarCanal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EliminarCanal(object):
    def setupUi(self, EliminarCanal):
        EliminarCanal.setObjectName("EliminarCanal")
        EliminarCanal.resize(422, 352)
        self.cancelar = QtWidgets.QPushButton(EliminarCanal)
        self.cancelar.setGeometry(QtCore.QRect(272, 280, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelar.setFont(font)
        self.cancelar.setObjectName("cancelar")
        self.eliminar = QtWidgets.QPushButton(EliminarCanal)
        self.eliminar.setGeometry(QtCore.QRect(50, 280, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.eliminar.setFont(font)
        self.eliminar.setObjectName("eliminar")
        self.label_91 = QtWidgets.QLabel(EliminarCanal)
        self.label_91.setGeometry(QtCore.QRect(50, 30, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setWordWrap(True)
        self.label_91.setObjectName("label_91")
        self.label_3 = QtWidgets.QLabel(EliminarCanal)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.nombre = QtWidgets.QLabel(EliminarCanal)
        self.nombre.setGeometry(QtCore.QRect(160, 130, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nombre.setFont(font)
        self.nombre.setText("")
        self.nombre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nombre.setObjectName("nombre")
        self.osciloscopio = QtWidgets.QLabel(EliminarCanal)
        self.osciloscopio.setGeometry(QtCore.QRect(160, 160, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.osciloscopio.setFont(font)
        self.osciloscopio.setText("")
        self.osciloscopio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.osciloscopio.setObjectName("osciloscopio")
        self.label_4 = QtWidgets.QLabel(EliminarCanal)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.canal = QtWidgets.QLabel(EliminarCanal)
        self.canal.setGeometry(QtCore.QRect(160, 190, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.canal.setFont(font)
        self.canal.setText("")
        self.canal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.canal.setObjectName("canal")
        self.label_5 = QtWidgets.QLabel(EliminarCanal)
        self.label_5.setGeometry(QtCore.QRect(50, 190, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(EliminarCanal)
        QtCore.QMetaObject.connectSlotsByName(EliminarCanal)

    def retranslateUi(self, EliminarCanal):
        _translate = QtCore.QCoreApplication.translate
        EliminarCanal.setWindowTitle(_translate("EliminarCanal", "Dialog"))
        self.cancelar.setText(_translate("EliminarCanal", "Cancelar"))
        self.eliminar.setText(_translate("EliminarCanal", "Eliminar"))
        self.label_91.setText(_translate("EliminarCanal", "¿Eliminar este canal?"))
        self.label_3.setText(_translate("EliminarCanal", "Nombre"))
        self.label_4.setText(_translate("EliminarCanal", "Osciloscopio"))
        self.label_5.setText(_translate("EliminarCanal", "Canal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EliminarCanal = QtWidgets.QDialog()
    ui = Ui_EliminarCanal()
    ui.setupUi(EliminarCanal)
    EliminarCanal.show()
    sys.exit(app.exec_())
