# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\eliminarParametro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EliminarParametro(object):
    def setupUi(self, EliminarParametro):
        EliminarParametro.setObjectName("EliminarParametro")
        EliminarParametro.resize(423, 346)
        self.cancelar = QtWidgets.QPushButton(EliminarParametro)
        self.cancelar.setGeometry(QtCore.QRect(272, 280, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelar.setFont(font)
        self.cancelar.setObjectName("cancelar")
        self.eliminar = QtWidgets.QPushButton(EliminarParametro)
        self.eliminar.setGeometry(QtCore.QRect(50, 280, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.eliminar.setFont(font)
        self.eliminar.setObjectName("eliminar")
        self.label_91 = QtWidgets.QLabel(EliminarParametro)
        self.label_91.setGeometry(QtCore.QRect(50, 30, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setWordWrap(True)
        self.label_91.setObjectName("label_91")
        self.label_3 = QtWidgets.QLabel(EliminarParametro)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.parametro = QtWidgets.QLabel(EliminarParametro)
        self.parametro.setGeometry(QtCore.QRect(160, 130, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.parametro.setFont(font)
        self.parametro.setText("")
        self.parametro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.parametro.setObjectName("parametro")
        self.valor = QtWidgets.QLabel(EliminarParametro)
        self.valor.setGeometry(QtCore.QRect(160, 160, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.valor.setFont(font)
        self.valor.setText("")
        self.valor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valor.setObjectName("valor")
        self.label_4 = QtWidgets.QLabel(EliminarParametro)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.unidad = QtWidgets.QLabel(EliminarParametro)
        self.unidad.setGeometry(QtCore.QRect(160, 190, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.unidad.setFont(font)
        self.unidad.setText("")
        self.unidad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unidad.setObjectName("unidad")
        self.label_5 = QtWidgets.QLabel(EliminarParametro)
        self.label_5.setGeometry(QtCore.QRect(50, 190, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.datapoint = QtWidgets.QLabel(EliminarParametro)
        self.datapoint.setGeometry(QtCore.QRect(160, 220, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.datapoint.setFont(font)
        self.datapoint.setText("")
        self.datapoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.datapoint.setObjectName("datapoint")
        self.label_6 = QtWidgets.QLabel(EliminarParametro)
        self.label_6.setGeometry(QtCore.QRect(50, 220, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(EliminarParametro)
        QtCore.QMetaObject.connectSlotsByName(EliminarParametro)

    def retranslateUi(self, EliminarParametro):
        _translate = QtCore.QCoreApplication.translate
        EliminarParametro.setWindowTitle(_translate("EliminarParametro", "Dialog"))
        self.cancelar.setText(_translate("EliminarParametro", "Cancelar"))
        self.eliminar.setText(_translate("EliminarParametro", "Eliminar"))
        self.label_91.setText(_translate("EliminarParametro", "¿Eliminar este valor?"))
        self.label_3.setText(_translate("EliminarParametro", "Parametro"))
        self.label_4.setText(_translate("EliminarParametro", "Valor"))
        self.label_5.setText(_translate("EliminarParametro", "Unidad"))
        self.label_6.setText(_translate("EliminarParametro", "Datapoint"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EliminarParametro = QtWidgets.QDialog()
    ui = Ui_EliminarParametro()
    ui.setupUi(EliminarParametro)
    EliminarParametro.show()
    sys.exit(app.exec_())
