# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ventanaPrincipal.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QCheckBox, QComboBox,
    QFrame, QHeaderView, QLabel, QLineEdit,
    QPlainTextEdit, QPushButton, QSizePolicy, QTabWidget,
    QTextBrowser, QTreeWidget, QTreeWidgetItem, QWidget)

from pyqtgraph import PlotWidget

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(1120, 668)
        self.tabWidget = QTabWidget(Widget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1121, 651))
        font = QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QSize(50, 50))
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.ingreso_parametros = QTreeWidget(self.tab_10)
        self.ingreso_parametros.setObjectName(u"ingreso_parametros")
        self.ingreso_parametros.setGeometry(QRect(520, 450, 591, 161))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.ingreso_parametros.setFont(font1)
        self.ingreso_parametros.setSortingEnabled(True)
        self.ingreso_parametros.header().setCascadingSectionResizes(False)
        self.ingreso_parametros.header().setDefaultSectionSize(110)
        self.label_26 = QLabel(self.tab_10)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 480, 91, 20))
        self.label_26.setFont(font1)
        self.ingreso_descripcion = QPlainTextEdit(self.tab_10)
        self.ingreso_descripcion.setObjectName(u"ingreso_descripcion")
        self.ingreso_descripcion.setGeometry(QRect(520, 340, 591, 61))
        self.ingreso_descripcion.setFont(font1)
        self.ingreso_crear_parametro = QPushButton(self.tab_10)
        self.ingreso_crear_parametro.setObjectName(u"ingreso_crear_parametro")
        self.ingreso_crear_parametro.setGeometry(QRect(320, 410, 191, 31))
        self.ingreso_crear_parametro.setFont(font1)
        self.label_28 = QLabel(self.tab_10)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(520, 430, 91, 20))
        self.label_28.setFont(font)
        self.ingreso_guardar_descripcion = QPushButton(self.tab_10)
        self.ingreso_guardar_descripcion.setObjectName(u"ingreso_guardar_descripcion")
        self.ingreso_guardar_descripcion.setGeometry(QRect(950, 300, 161, 31))
        self.ingreso_guardar_descripcion.setFont(font1)
        self.label_29 = QLabel(self.tab_10)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(520, 320, 161, 20))
        self.label_29.setFont(font)
        self.ingreso_seleccionar_carpeta = QPushButton(self.tab_10)
        self.ingreso_seleccionar_carpeta.setObjectName(u"ingreso_seleccionar_carpeta")
        self.ingreso_seleccionar_carpeta.setGeometry(QRect(10, 30, 181, 31))
        self.ingreso_seleccionar_carpeta.setFont(font1)
        self.ingreso_archivos_locales = QTreeWidget(self.tab_10)
        self.ingreso_archivos_locales.setObjectName(u"ingreso_archivos_locales")
        self.ingreso_archivos_locales.setGeometry(QRect(10, 120, 501, 281))
        self.ingreso_archivos_locales.setFont(font1)
        self.ingreso_archivos_locales.setSortingEnabled(True)
        self.ingreso_archivos_locales.header().setDefaultSectionSize(90)
        self.ingreso_refrescar = QPushButton(self.tab_10)
        self.ingreso_refrescar.setObjectName(u"ingreso_refrescar")
        self.ingreso_refrescar.setGeometry(QRect(210, 20, 151, 31))
        self.ingreso_refrescar.setFont(font1)
        self.ingreso_eliminar_archivo = QPushButton(self.tab_10)
        self.ingreso_eliminar_archivo.setObjectName(u"ingreso_eliminar_archivo")
        self.ingreso_eliminar_archivo.setGeometry(QRect(370, 60, 141, 31))
        self.ingreso_eliminar_archivo.setFont(font1)
        self.label_84 = QLabel(self.tab_10)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(10, 80, 111, 20))
        self.label_84.setFont(font)
        self.label_84.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ingreso_label_archivos_locales = QLabel(self.tab_10)
        self.ingreso_label_archivos_locales.setObjectName(u"ingreso_label_archivos_locales")
        self.ingreso_label_archivos_locales.setGeometry(QRect(10, 100, 501, 20))
        self.ingreso_label_archivos_locales.setFont(font1)
        self.ingreso_label_archivos_locales.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ingreso_agregar_archivo = QPushButton(self.tab_10)
        self.ingreso_agregar_archivo.setObjectName(u"ingreso_agregar_archivo")
        self.ingreso_agregar_archivo.setGeometry(QRect(370, 20, 141, 31))
        self.ingreso_agregar_archivo.setFont(font1)
        self.label_87 = QLabel(self.tab_10)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(10, 540, 91, 20))
        self.label_87.setFont(font1)
        self.label_88 = QLabel(self.tab_10)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setGeometry(QRect(10, 450, 91, 20))
        self.label_88.setFont(font1)
        self.label_89 = QLabel(self.tab_10)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setGeometry(QRect(10, 510, 91, 20))
        self.label_89.setFont(font1)
        self.ingreso_agregar_parametro_1 = QPushButton(self.tab_10)
        self.ingreso_agregar_parametro_1.setObjectName(u"ingreso_agregar_parametro_1")
        self.ingreso_agregar_parametro_1.setGeometry(QRect(80, 570, 101, 31))
        self.ingreso_agregar_parametro_1.setFont(font1)
        self.ingreso_parametro_parametro_1 = QComboBox(self.tab_10)
        self.ingreso_parametro_parametro_1.addItem("")
        self.ingreso_parametro_parametro_1.addItem("")
        self.ingreso_parametro_parametro_1.addItem("")
        self.ingreso_parametro_parametro_1.addItem("")
        self.ingreso_parametro_parametro_1.setObjectName(u"ingreso_parametro_parametro_1")
        self.ingreso_parametro_parametro_1.setGeometry(QRect(80, 510, 101, 21))
        self.ingreso_parametro_parametro_1.setFont(font1)
        self.ingreso_agregar_parametro_2 = QPushButton(self.tab_10)
        self.ingreso_agregar_parametro_2.setObjectName(u"ingreso_agregar_parametro_2")
        self.ingreso_agregar_parametro_2.setGeometry(QRect(190, 570, 101, 31))
        self.ingreso_agregar_parametro_2.setFont(font1)
        self.ingreso_parametro_parametro_2 = QComboBox(self.tab_10)
        self.ingreso_parametro_parametro_2.addItem("")
        self.ingreso_parametro_parametro_2.addItem("")
        self.ingreso_parametro_parametro_2.addItem("")
        self.ingreso_parametro_parametro_2.addItem("")
        self.ingreso_parametro_parametro_2.setObjectName(u"ingreso_parametro_parametro_2")
        self.ingreso_parametro_parametro_2.setGeometry(QRect(190, 510, 101, 21))
        self.ingreso_parametro_parametro_2.setFont(font1)
        self.ingreso_agregar_parametro_3 = QPushButton(self.tab_10)
        self.ingreso_agregar_parametro_3.setObjectName(u"ingreso_agregar_parametro_3")
        self.ingreso_agregar_parametro_3.setGeometry(QRect(300, 570, 101, 31))
        self.ingreso_agregar_parametro_3.setFont(font1)
        self.ingreso_parametro_parametro_3 = QComboBox(self.tab_10)
        self.ingreso_parametro_parametro_3.addItem("")
        self.ingreso_parametro_parametro_3.addItem("")
        self.ingreso_parametro_parametro_3.addItem("")
        self.ingreso_parametro_parametro_3.addItem("")
        self.ingreso_parametro_parametro_3.setObjectName(u"ingreso_parametro_parametro_3")
        self.ingreso_parametro_parametro_3.setGeometry(QRect(300, 510, 101, 21))
        self.ingreso_parametro_parametro_3.setFont(font1)
        self.ingreso_agregar_parametro_4 = QPushButton(self.tab_10)
        self.ingreso_agregar_parametro_4.setObjectName(u"ingreso_agregar_parametro_4")
        self.ingreso_agregar_parametro_4.setGeometry(QRect(410, 570, 101, 31))
        self.ingreso_agregar_parametro_4.setFont(font1)
        self.ingreso_parametro_parametro_4 = QComboBox(self.tab_10)
        self.ingreso_parametro_parametro_4.addItem("")
        self.ingreso_parametro_parametro_4.addItem("")
        self.ingreso_parametro_parametro_4.addItem("")
        self.ingreso_parametro_parametro_4.addItem("")
        self.ingreso_parametro_parametro_4.setObjectName(u"ingreso_parametro_parametro_4")
        self.ingreso_parametro_parametro_4.setGeometry(QRect(410, 510, 101, 21))
        self.ingreso_parametro_parametro_4.setFont(font1)
        self.label_91 = QLabel(self.tab_10)
        self.label_91.setObjectName(u"label_91")
        self.label_91.setGeometry(QRect(10, 420, 191, 21))
        self.label_91.setFont(font)
        self.label_91.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ingreso_eliminar_parametro = QPushButton(self.tab_10)
        self.ingreso_eliminar_parametro.setObjectName(u"ingreso_eliminar_parametro")
        self.ingreso_eliminar_parametro.setGeometry(QRect(960, 410, 151, 31))
        self.ingreso_eliminar_parametro.setFont(font1)
        self.ingreso_asignar_datapoint = QPushButton(self.tab_10)
        self.ingreso_asignar_datapoint.setObjectName(u"ingreso_asignar_datapoint")
        self.ingreso_asignar_datapoint.setGeometry(QRect(210, 60, 151, 31))
        self.ingreso_asignar_datapoint.setFont(font1)
        self.ingreso_datapoint_parametro_1 = QLineEdit(self.tab_10)
        self.ingreso_datapoint_parametro_1.setObjectName(u"ingreso_datapoint_parametro_1")
        self.ingreso_datapoint_parametro_1.setGeometry(QRect(80, 450, 101, 21))
        self.ingreso_datapoint_parametro_1.setFont(font1)
        self.ingreso_unidad_parametro_1 = QLineEdit(self.tab_10)
        self.ingreso_unidad_parametro_1.setObjectName(u"ingreso_unidad_parametro_1")
        self.ingreso_unidad_parametro_1.setGeometry(QRect(80, 480, 101, 21))
        self.ingreso_unidad_parametro_1.setFont(font1)
        self.ingreso_valor_parametro_1 = QLineEdit(self.tab_10)
        self.ingreso_valor_parametro_1.setObjectName(u"ingreso_valor_parametro_1")
        self.ingreso_valor_parametro_1.setGeometry(QRect(80, 540, 101, 21))
        self.ingreso_valor_parametro_1.setFont(font1)
        self.ingreso_datapoint_parametro_2 = QLineEdit(self.tab_10)
        self.ingreso_datapoint_parametro_2.setObjectName(u"ingreso_datapoint_parametro_2")
        self.ingreso_datapoint_parametro_2.setGeometry(QRect(190, 450, 101, 21))
        self.ingreso_datapoint_parametro_2.setFont(font1)
        self.ingreso_unidad_parametro_2 = QLineEdit(self.tab_10)
        self.ingreso_unidad_parametro_2.setObjectName(u"ingreso_unidad_parametro_2")
        self.ingreso_unidad_parametro_2.setGeometry(QRect(190, 480, 101, 21))
        self.ingreso_unidad_parametro_2.setFont(font1)
        self.ingreso_valor_parametro_2 = QLineEdit(self.tab_10)
        self.ingreso_valor_parametro_2.setObjectName(u"ingreso_valor_parametro_2")
        self.ingreso_valor_parametro_2.setGeometry(QRect(190, 540, 101, 21))
        self.ingreso_valor_parametro_2.setFont(font1)
        self.ingreso_datapoint_parametro_3 = QLineEdit(self.tab_10)
        self.ingreso_datapoint_parametro_3.setObjectName(u"ingreso_datapoint_parametro_3")
        self.ingreso_datapoint_parametro_3.setGeometry(QRect(300, 450, 101, 21))
        self.ingreso_datapoint_parametro_3.setFont(font1)
        self.ingreso_unidad_parametro_3 = QLineEdit(self.tab_10)
        self.ingreso_unidad_parametro_3.setObjectName(u"ingreso_unidad_parametro_3")
        self.ingreso_unidad_parametro_3.setGeometry(QRect(300, 480, 101, 21))
        self.ingreso_unidad_parametro_3.setFont(font1)
        self.ingreso_valor_parametro_3 = QLineEdit(self.tab_10)
        self.ingreso_valor_parametro_3.setObjectName(u"ingreso_valor_parametro_3")
        self.ingreso_valor_parametro_3.setGeometry(QRect(300, 540, 101, 21))
        self.ingreso_valor_parametro_3.setFont(font1)
        self.ingreso_datapoint_parametro_4 = QLineEdit(self.tab_10)
        self.ingreso_datapoint_parametro_4.setObjectName(u"ingreso_datapoint_parametro_4")
        self.ingreso_datapoint_parametro_4.setGeometry(QRect(410, 450, 101, 21))
        self.ingreso_datapoint_parametro_4.setFont(font1)
        self.ingreso_unidad_parametro_4 = QLineEdit(self.tab_10)
        self.ingreso_unidad_parametro_4.setObjectName(u"ingreso_unidad_parametro_4")
        self.ingreso_unidad_parametro_4.setGeometry(QRect(410, 480, 101, 21))
        self.ingreso_unidad_parametro_4.setFont(font1)
        self.ingreso_valor_parametro_4 = QLineEdit(self.tab_10)
        self.ingreso_valor_parametro_4.setObjectName(u"ingreso_valor_parametro_4")
        self.ingreso_valor_parametro_4.setGeometry(QRect(410, 540, 101, 21))
        self.ingreso_valor_parametro_4.setFont(font1)
        self.label_17 = QLabel(self.tab_10)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(520, 10, 161, 20))
        self.label_17.setFont(font)
        self.frame_2 = QFrame(self.tab_10)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(520, 30, 591, 261))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.ingreso_preview_graph = PlotWidget(self.frame_2)
        self.ingreso_preview_graph.setObjectName(u"ingreso_preview_graph")
        self.ingreso_preview_graph.setGeometry(QRect(0, 0, 591, 261))
        self.ingreso_preview_graph.setFont(font1)
        self.ingreso_preview_graph.setAutoFillBackground(False)
        self.ingreso_preview_image = QLabel(self.frame_2)
        self.ingreso_preview_image.setObjectName(u"ingreso_preview_image")
        self.ingreso_preview_image.setGeometry(QRect(0, 0, 591, 261))
        self.ingreso_preview_image.setFont(font1)
        self.ingreso_preview_image.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ingreso_preview_text = QTextBrowser(self.frame_2)
        self.ingreso_preview_text.setObjectName(u"ingreso_preview_text")
        self.ingreso_preview_text.setGeometry(QRect(0, 0, 591, 261))
        self.ingreso_preview_text.setFont(font1)
        self.ingreso_label_preview = QLabel(self.tab_10)
        self.ingreso_label_preview.setObjectName(u"ingreso_label_preview")
        self.ingreso_label_preview.setGeometry(QRect(580, 10, 531, 20))
        self.ingreso_label_preview.setFont(font1)
        self.ingreso_label_preview.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.tabWidget.addTab(self.tab_10, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_12 = QLabel(self.tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 80, 271, 20))
        self.label_12.setFont(font)
        self.dispositivos_buscar = QPushButton(self.tab)
        self.dispositivos_buscar.setObjectName(u"dispositivos_buscar")
        self.dispositivos_buscar.setGeometry(QRect(330, 40, 191, 31))
        self.dispositivos_buscar.setFont(font1)
        self.label_13 = QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 340, 261, 20))
        self.label_13.setFont(font)
        self.dispositivos_agregar_ip = QPushButton(self.tab)
        self.dispositivos_agregar_ip.setObjectName(u"dispositivos_agregar_ip")
        self.dispositivos_agregar_ip.setGeometry(QRect(30, 300, 181, 31))
        self.dispositivos_agregar_ip.setFont(font1)
        self.label_14 = QLabel(self.tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(550, 80, 71, 20))
        self.label_14.setFont(font)
        self.dispositivos_desconectar = QPushButton(self.tab)
        self.dispositivos_desconectar.setObjectName(u"dispositivos_desconectar")
        self.dispositivos_desconectar.setGeometry(QRect(330, 300, 191, 31))
        self.dispositivos_desconectar.setFont(font1)
        self.dispositivos_conectar = QPushButton(self.tab)
        self.dispositivos_conectar.setObjectName(u"dispositivos_conectar")
        self.dispositivos_conectar.setGeometry(QRect(30, 40, 171, 31))
        self.dispositivos_conectar.setFont(font1)
        self.dispositivos_eliminar_canal = QPushButton(self.tab)
        self.dispositivos_eliminar_canal.setObjectName(u"dispositivos_eliminar_canal")
        self.dispositivos_eliminar_canal.setGeometry(QRect(550, 40, 131, 31))
        self.dispositivos_eliminar_canal.setFont(font1)
        self.dispositivos_agregar_canal = QPushButton(self.tab)
        self.dispositivos_agregar_canal.setObjectName(u"dispositivos_agregar_canal")
        self.dispositivos_agregar_canal.setGeometry(QRect(970, 40, 121, 31))
        self.dispositivos_agregar_canal.setFont(font1)
        self.dispositivos_canales = QTreeWidget(self.tab)
        self.dispositivos_canales.setObjectName(u"dispositivos_canales")
        self.dispositivos_canales.setGeometry(QRect(550, 100, 541, 441))
        self.dispositivos_canales.setFont(font1)
        self.dispositivos_canales.setSortingEnabled(True)
        self.dispositivos_dispositivos_conectados = QTreeWidget(self.tab)
        self.dispositivos_dispositivos_conectados.setObjectName(u"dispositivos_dispositivos_conectados")
        self.dispositivos_dispositivos_conectados.setGeometry(QRect(30, 360, 491, 231))
        self.dispositivos_dispositivos_conectados.setFont(font1)
        self.dispositivos_dispositivos_conectados.setSortingEnabled(True)
        self.dispositivos_dispositivos_conectados.header().setDefaultSectionSize(110)
        self.dispositivos_dispositivos_disponibles = QTreeWidget(self.tab)
        self.dispositivos_dispositivos_disponibles.setObjectName(u"dispositivos_dispositivos_disponibles")
        self.dispositivos_dispositivos_disponibles.setGeometry(QRect(30, 100, 491, 171))
        self.dispositivos_dispositivos_disponibles.setFont(font1)
        self.dispositivos_dispositivos_disponibles.setSortingEnabled(True)
        self.status_2 = QLabel(self.tab)
        self.status_2.setObjectName(u"status_2")
        self.status_2.setGeometry(QRect(10, 630, 21, 20))
        self.dispositivos_guardar_perfil = QPushButton(self.tab)
        self.dispositivos_guardar_perfil.setObjectName(u"dispositivos_guardar_perfil")
        self.dispositivos_guardar_perfil.setGeometry(QRect(550, 560, 181, 31))
        self.dispositivos_guardar_perfil.setFont(font1)
        self.dispositivos_cargar_perfil = QPushButton(self.tab)
        self.dispositivos_cargar_perfil.setObjectName(u"dispositivos_cargar_perfil")
        self.dispositivos_cargar_perfil.setGeometry(QRect(910, 560, 181, 31))
        self.dispositivos_cargar_perfil.setFont(font1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.adquisicion_label_archivos_locales = QLabel(self.tab_2)
        self.adquisicion_label_archivos_locales.setObjectName(u"adquisicion_label_archivos_locales")
        self.adquisicion_label_archivos_locales.setGeometry(QRect(20, 80, 481, 20))
        self.adquisicion_label_archivos_locales.setFont(font1)
        self.adquisicion_label_archivos_locales.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_8 = QLabel(self.tab_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(510, 50, 131, 20))
        self.label_8.setFont(font)
        self.adquisicion_seleccionar_carpeta = QPushButton(self.tab_2)
        self.adquisicion_seleccionar_carpeta.setObjectName(u"adquisicion_seleccionar_carpeta")
        self.adquisicion_seleccionar_carpeta.setGeometry(QRect(20, 20, 241, 31))
        self.adquisicion_seleccionar_carpeta.setFont(font1)
        self.adquisicion_auto = QPushButton(self.tab_2)
        self.adquisicion_auto.setObjectName(u"adquisicion_auto")
        self.adquisicion_auto.setGeometry(QRect(520, 450, 161, 41))
        self.adquisicion_auto.setFont(font1)
        self.adquisicion_adquirir = QPushButton(self.tab_2)
        self.adquisicion_adquirir.setObjectName(u"adquisicion_adquirir")
        self.adquisicion_adquirir.setGeometry(QRect(620, 340, 121, 41))
        self.adquisicion_adquirir.setFont(font1)
        self.adquisicion_auto_imagenes = QCheckBox(self.tab_2)
        self.adquisicion_auto_imagenes.setObjectName(u"adquisicion_auto_imagenes")
        self.adquisicion_auto_imagenes.setGeometry(QRect(730, 510, 221, 26))
        self.adquisicion_auto_imagenes.setFont(font1)
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(730, 540, 301, 20))
        self.label_9.setFont(font1)
        self.adquisicion_seleccionar_carpeta_imagenes = QPushButton(self.tab_2)
        self.adquisicion_seleccionar_carpeta_imagenes.setObjectName(u"adquisicion_seleccionar_carpeta_imagenes")
        self.adquisicion_seleccionar_carpeta_imagenes.setGeometry(QRect(950, 510, 151, 31))
        self.adquisicion_seleccionar_carpeta_imagenes.setFont(font1)
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(520, 510, 151, 20))
        self.label_11.setFont(font)
        self.adquisicion_fuente_trigger = QComboBox(self.tab_2)
        self.adquisicion_fuente_trigger.setObjectName(u"adquisicion_fuente_trigger")
        self.adquisicion_fuente_trigger.setGeometry(QRect(520, 530, 161, 21))
        self.adquisicion_fuente_trigger.setFont(font1)
        self.adquisicion_guardar = QPushButton(self.tab_2)
        self.adquisicion_guardar.setObjectName(u"adquisicion_guardar")
        self.adquisicion_guardar.setGeometry(QRect(910, 340, 121, 41))
        self.adquisicion_guardar.setFont(font1)
        self.label_22 = QLabel(self.tab_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 60, 121, 20))
        self.label_22.setFont(font)
        self.label_22.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.adquisicion_archivos_locales = QTreeWidget(self.tab_2)
        self.adquisicion_archivos_locales.setObjectName(u"adquisicion_archivos_locales")
        self.adquisicion_archivos_locales.setGeometry(QRect(20, 100, 471, 231))
        self.adquisicion_archivos_locales.setFont(font1)
        self.label_10 = QLabel(self.tab_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 340, 301, 20))
        self.label_10.setFont(font)
        self.adquisicion_refrescar = QPushButton(self.tab_2)
        self.adquisicion_refrescar.setObjectName(u"adquisicion_refrescar")
        self.adquisicion_refrescar.setGeometry(QRect(390, 20, 101, 31))
        self.adquisicion_refrescar.setFont(font1)
        self.adquisicion_auto_guardar = QCheckBox(self.tab_2)
        self.adquisicion_auto_guardar.setObjectName(u"adquisicion_auto_guardar")
        self.adquisicion_auto_guardar.setGeometry(QRect(730, 450, 231, 26))
        self.adquisicion_auto_guardar.setFont(font1)
        self.adquisicion_label_carpeta_imagenes = QLabel(self.tab_2)
        self.adquisicion_label_carpeta_imagenes.setObjectName(u"adquisicion_label_carpeta_imagenes")
        self.adquisicion_label_carpeta_imagenes.setGeometry(QRect(730, 560, 371, 20))
        self.adquisicion_label_carpeta_imagenes.setFont(font1)
        self.adquisicion_origen_datos = QTreeWidget(self.tab_2)
        self.adquisicion_origen_datos.setObjectName(u"adquisicion_origen_datos")
        self.adquisicion_origen_datos.setGeometry(QRect(20, 360, 471, 231))
        self.adquisicion_origen_datos.setFont(font1)
        self.adquisicion_label_preview = QLabel(self.tab_2)
        self.adquisicion_label_preview.setObjectName(u"adquisicion_label_preview")
        self.adquisicion_label_preview.setGeometry(QRect(590, 50, 511, 20))
        self.adquisicion_label_preview.setFont(font1)
        self.adquisicion_label_preview.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame = QFrame(self.tab_2)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(510, 70, 591, 261))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.adquisicion_preview_graph = PlotWidget(self.frame)
        self.adquisicion_preview_graph.setObjectName(u"adquisicion_preview_graph")
        self.adquisicion_preview_graph.setGeometry(QRect(0, 0, 591, 261))
        self.adquisicion_preview_graph.setFont(font1)
        self.adquisicion_preview_graph.setAutoFillBackground(False)
        self.adquisicion_preview_image = QLabel(self.frame)
        self.adquisicion_preview_image.setObjectName(u"adquisicion_preview_image")
        self.adquisicion_preview_image.setGeometry(QRect(0, 0, 591, 261))
        self.adquisicion_preview_image.setFont(font1)
        self.adquisicion_preview_image.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.adquisicion_preview_text = QTextBrowser(self.frame)
        self.adquisicion_preview_text.setObjectName(u"adquisicion_preview_text")
        self.adquisicion_preview_text.setGeometry(QRect(0, 0, 591, 261))
        self.adquisicion_preview_text.setFont(font1)
        self.label_23 = QLabel(self.tab_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(900, 20, 81, 20))
        self.label_23.setFont(font)
        self.adquisicion_prefijo = QLineEdit(self.tab_2)
        self.adquisicion_prefijo.setObjectName(u"adquisicion_prefijo")
        self.adquisicion_prefijo.setGeometry(QRect(980, 20, 121, 21))
        self.adquisicion_prefijo.setFont(font1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.bd_seleccionar_carpeta = QPushButton(self.tab_3)
        self.bd_seleccionar_carpeta.setObjectName(u"bd_seleccionar_carpeta")
        self.bd_seleccionar_carpeta.setGeometry(QRect(10, 20, 221, 31))
        self.bd_seleccionar_carpeta.setFont(font1)
        self.bd_subir = QPushButton(self.tab_3)
        self.bd_subir.setObjectName(u"bd_subir")
        self.bd_subir.setGeometry(QRect(900, 150, 191, 31))
        self.bd_subir.setFont(font1)
        self.bd_label_archivos_locales = QLabel(self.tab_3)
        self.bd_label_archivos_locales.setObjectName(u"bd_label_archivos_locales")
        self.bd_label_archivos_locales.setGeometry(QRect(10, 200, 561, 20))
        self.bd_label_archivos_locales.setFont(font1)
        self.bd_label_archivos_locales.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_3 = QLabel(self.tab_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(900, 30, 101, 20))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.tab_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(900, 80, 91, 20))
        self.label_4.setFont(font)
        self.bd_experimento = QComboBox(self.tab_3)
        self.bd_experimento.addItem("")
        self.bd_experimento.setObjectName(u"bd_experimento")
        self.bd_experimento.setGeometry(QRect(900, 50, 161, 21))
        self.bd_experimento.setFont(font1)
        self.bd_jornada = QComboBox(self.tab_3)
        self.bd_jornada.addItem("")
        self.bd_jornada.addItem("")
        self.bd_jornada.addItem("")
        self.bd_jornada.setObjectName(u"bd_jornada")
        self.bd_jornada.setGeometry(QRect(900, 100, 161, 21))
        self.bd_jornada.setFont(font1)
        self.bd_agregar_experimento = QPushButton(self.tab_3)
        self.bd_agregar_experimento.setObjectName(u"bd_agregar_experimento")
        self.bd_agregar_experimento.setGeometry(QRect(1070, 50, 21, 21))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.bd_agregar_experimento.setFont(font2)
        self.bd_agregar_jornada = QPushButton(self.tab_3)
        self.bd_agregar_jornada.setObjectName(u"bd_agregar_jornada")
        self.bd_agregar_jornada.setGeometry(QRect(1070, 100, 21, 21))
        self.bd_agregar_jornada.setFont(font2)
        self.label_5 = QLabel(self.tab_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(590, 80, 91, 20))
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.tab_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(590, 200, 151, 20))
        self.label_6.setFont(font)
        self.bd_archivos_servidor = QTreeWidget(self.tab_3)
        self.bd_archivos_servidor.setObjectName(u"bd_archivos_servidor")
        self.bd_archivos_servidor.setGeometry(QRect(590, 220, 511, 191))
        self.bd_archivos_servidor.setFont(font1)
        self.bd_archivos_servidor.setSortingEnabled(True)
        self.bd_archivos_locales = QTreeWidget(self.tab_3)
        self.bd_archivos_locales.setObjectName(u"bd_archivos_locales")
        self.bd_archivos_locales.setEnabled(True)
        self.bd_archivos_locales.setGeometry(QRect(10, 220, 561, 191))
        self.bd_archivos_locales.setFont(font1)
        self.bd_archivos_locales.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.bd_archivos_locales.setIndentation(25)
        self.bd_archivos_locales.setRootIsDecorated(True)
        self.bd_archivos_locales.setSortingEnabled(True)
        self.bd_archivos_locales.setAnimated(False)
        self.bd_archivos_locales.setWordWrap(False)
        self.bd_archivos_locales.header().setCascadingSectionResizes(False)
        self.bd_archivos_locales.header().setProperty(u"showSortIndicator", True)
        self.bd_archivos_locales.header().setStretchLastSection(True)
        self.label_15 = QLabel(self.tab_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(590, 120, 91, 20))
        self.label_15.setFont(font)
        self.label_16 = QLabel(self.tab_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(590, 160, 91, 20))
        self.label_16.setFont(font)
        self.bd_refrescar = QPushButton(self.tab_3)
        self.bd_refrescar.setObjectName(u"bd_refrescar")
        self.bd_refrescar.setGeometry(QRect(360, 20, 211, 31))
        self.bd_refrescar.setFont(font1)
        self.label_18 = QLabel(self.tab_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 60, 221, 20))
        self.label_18.setFont(font)
        self.bd_parametros_locales = QTreeWidget(self.tab_3)
        self.bd_parametros_locales.setObjectName(u"bd_parametros_locales")
        self.bd_parametros_locales.setGeometry(QRect(10, 440, 561, 171))
        self.bd_parametros_locales.setFont(font1)
        self.bd_parametros_locales.setSortingEnabled(True)
        self.bd_parametros_locales.header().setDefaultSectionSize(100)
        self.label_20 = QLabel(self.tab_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 420, 301, 20))
        self.label_20.setFont(font)
        self.label_21 = QLabel(self.tab_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 180, 141, 20))
        self.label_21.setFont(font)
        self.label_21.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.bd_descripcion = QTextBrowser(self.tab_3)
        self.bd_descripcion.setObjectName(u"bd_descripcion")
        self.bd_descripcion.setGeometry(QRect(10, 80, 561, 91))
        self.bd_descripcion.setFont(font1)
        self.bd_refrescar_servidor = QPushButton(self.tab_3)
        self.bd_refrescar_servidor.setObjectName(u"bd_refrescar_servidor")
        self.bd_refrescar_servidor.setGeometry(QRect(590, 20, 271, 31))
        self.bd_refrescar_servidor.setFont(font1)
        self.label_24 = QLabel(self.tab_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(590, 420, 301, 20))
        self.label_24.setFont(font)
        self.bd_parametros_servidor = QTreeWidget(self.tab_3)
        self.bd_parametros_servidor.setObjectName(u"bd_parametros_servidor")
        self.bd_parametros_servidor.setGeometry(QRect(590, 440, 511, 171))
        self.bd_parametros_servidor.setFont(font1)
        self.bd_parametros_servidor.setSortingEnabled(True)
        self.bd_parametros_servidor.header().setDefaultSectionSize(100)
        self.bd_usuario = QLineEdit(self.tab_3)
        self.bd_usuario.setObjectName(u"bd_usuario")
        self.bd_usuario.setGeometry(QRect(710, 77, 151, 21))
        self.bd_usuario.setFont(font1)
        self.bd_password = QLineEdit(self.tab_3)
        self.bd_password.setObjectName(u"bd_password")
        self.bd_password.setGeometry(QRect(710, 120, 151, 21))
        self.bd_password.setFont(font1)
        self.bd_password.setEchoMode(QLineEdit.EchoMode.Password)
        self.bd_ip = QLineEdit(self.tab_3)
        self.bd_ip.setObjectName(u"bd_ip")
        self.bd_ip.setGeometry(QRect(710, 160, 151, 21))
        self.bd_ip.setFont(font1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.log = QTextBrowser(self.tab_6)
        self.log.setObjectName(u"log")
        self.log.setGeometry(QRect(20, 50, 1071, 551))
        self.log.setFont(font1)
        self.label_92 = QLabel(self.tab_6)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setGeometry(QRect(380, 10, 331, 31))
        self.label_92.setFont(font)
        self.label_92.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tabWidget.addTab(self.tab_6, "")
        self.status = QLabel(Widget)
        self.status.setObjectName(u"status")
        self.status.setGeometry(QRect(10, 650, 471, 20))
        font3 = QFont()
        font3.setBold(True)
        self.status.setFont(font3)

        self.retranslateUi(Widget)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        ___qtreewidgetitem = self.ingreso_parametros.headerItem()
        ___qtreewidgetitem.setText(4, QCoreApplication.translate("Widget", u"Tipo", None));
        ___qtreewidgetitem.setText(3, QCoreApplication.translate("Widget", u"Unidad", None));
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("Widget", u"Valor", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("Widget", u"Par\u00e1metro", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("Widget", u"Datapoint", None));
        self.label_26.setText(QCoreApplication.translate("Widget", u"Unidad", None))
        self.ingreso_descripcion.setPlainText("")
        self.ingreso_crear_parametro.setText(QCoreApplication.translate("Widget", u"Crear Nuevo Parametro", None))
        self.label_28.setText(QCoreApplication.translate("Widget", u"Parametros", None))
        self.ingreso_guardar_descripcion.setText(QCoreApplication.translate("Widget", u"Guardar Descripcion", None))
        self.label_29.setText(QCoreApplication.translate("Widget", u"Descripcion", None))
        self.ingreso_seleccionar_carpeta.setText(QCoreApplication.translate("Widget", u"Cambiar Carpeta Local", None))
        ___qtreewidgetitem1 = self.ingreso_archivos_locales.headerItem()
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("Widget", u"Filename", None));
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("Widget", u"Datapoint", None));
        self.ingreso_refrescar.setText(QCoreApplication.translate("Widget", u"Refrescar", None))
        self.ingreso_eliminar_archivo.setText(QCoreApplication.translate("Widget", u"Eliminar Archivo", None))
        self.label_84.setText(QCoreApplication.translate("Widget", u"Carpeta Local", None))
        self.ingreso_label_archivos_locales.setText("")
        self.ingreso_agregar_archivo.setText(QCoreApplication.translate("Widget", u"Agregar Archivo", None))
        self.label_87.setText(QCoreApplication.translate("Widget", u"Valor", None))
        self.label_88.setText(QCoreApplication.translate("Widget", u"Datapoint", None))
        self.label_89.setText(QCoreApplication.translate("Widget", u"Parametro", None))
        self.ingreso_agregar_parametro_1.setText(QCoreApplication.translate("Widget", u"Agregar", None))
        self.ingreso_parametro_parametro_1.setItemText(0, QCoreApplication.translate("Widget", u"Presion", None))
        self.ingreso_parametro_parametro_1.setItemText(1, QCoreApplication.translate("Widget", u"-", None))
        self.ingreso_parametro_parametro_1.setItemText(2, QCoreApplication.translate("Widget", u"Voltaje Descarga", None))
        self.ingreso_parametro_parametro_1.setItemText(3, QCoreApplication.translate("Widget", u"Gas", None))

        self.ingreso_agregar_parametro_2.setText(QCoreApplication.translate("Widget", u"Agregar", None))
        self.ingreso_parametro_parametro_2.setItemText(0, QCoreApplication.translate("Widget", u"Voltaje Descarga", None))
        self.ingreso_parametro_parametro_2.setItemText(1, QCoreApplication.translate("Widget", u"-", None))
        self.ingreso_parametro_parametro_2.setItemText(2, QCoreApplication.translate("Widget", u"Presion", None))
        self.ingreso_parametro_parametro_2.setItemText(3, QCoreApplication.translate("Widget", u"Gas", None))

        self.ingreso_agregar_parametro_3.setText(QCoreApplication.translate("Widget", u"Agregar", None))
        self.ingreso_parametro_parametro_3.setItemText(0, QCoreApplication.translate("Widget", u"Gas", None))
        self.ingreso_parametro_parametro_3.setItemText(1, QCoreApplication.translate("Widget", u"-", None))
        self.ingreso_parametro_parametro_3.setItemText(2, QCoreApplication.translate("Widget", u"Presion", None))
        self.ingreso_parametro_parametro_3.setItemText(3, QCoreApplication.translate("Widget", u"Voltaje Descarga", None))

        self.ingreso_agregar_parametro_4.setText(QCoreApplication.translate("Widget", u"Agregar", None))
        self.ingreso_parametro_parametro_4.setItemText(0, QCoreApplication.translate("Widget", u"-", None))
        self.ingreso_parametro_parametro_4.setItemText(1, QCoreApplication.translate("Widget", u"Presion", None))
        self.ingreso_parametro_parametro_4.setItemText(2, QCoreApplication.translate("Widget", u"Voltaje Descarga", None))
        self.ingreso_parametro_parametro_4.setItemText(3, QCoreApplication.translate("Widget", u"Gas", None))

        self.label_91.setText(QCoreApplication.translate("Widget", u"Ingreso de Parametros", None))
        self.ingreso_eliminar_parametro.setText(QCoreApplication.translate("Widget", u"Eliminar Parametro", None))
        self.ingreso_asignar_datapoint.setText(QCoreApplication.translate("Widget", u"Asignar Datapoint", None))
        self.ingreso_datapoint_parametro_1.setText("")
        self.ingreso_unidad_parametro_1.setText("")
        self.ingreso_valor_parametro_1.setText("")
        self.ingreso_datapoint_parametro_2.setText("")
        self.ingreso_unidad_parametro_2.setText("")
        self.ingreso_valor_parametro_2.setText("")
        self.ingreso_datapoint_parametro_3.setText("")
        self.ingreso_unidad_parametro_3.setText("")
        self.ingreso_valor_parametro_3.setText("")
        self.ingreso_datapoint_parametro_4.setText("")
        self.ingreso_unidad_parametro_4.setText("")
        self.ingreso_valor_parametro_4.setText("")
        self.label_17.setText(QCoreApplication.translate("Widget", u"Preview", None))
        self.ingreso_preview_image.setText("")
        self.ingreso_preview_text.setHtml(QCoreApplication.translate("Widget", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.ingreso_label_preview.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), QCoreApplication.translate("Widget", u"Ingreso Manual", None))
        self.label_12.setText(QCoreApplication.translate("Widget", u"Osciloscopios USB Disponibles", None))
        self.dispositivos_buscar.setText(QCoreApplication.translate("Widget", u"Buscar USB", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"Osciloscopios Conectados", None))
        self.dispositivos_agregar_ip.setText(QCoreApplication.translate("Widget", u"Conectar por LAN", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"Canales", None))
        self.dispositivos_desconectar.setText(QCoreApplication.translate("Widget", u"Desconectar Osciloscopio", None))
        self.dispositivos_conectar.setText(QCoreApplication.translate("Widget", u"Conectar USB", None))
        self.dispositivos_eliminar_canal.setText(QCoreApplication.translate("Widget", u"Eliminar Canal", None))
        self.dispositivos_agregar_canal.setText(QCoreApplication.translate("Widget", u"Agregar Canal", None))
        ___qtreewidgetitem2 = self.dispositivos_canales.headerItem()
        ___qtreewidgetitem2.setText(3, QCoreApplication.translate("Widget", u"Datapoints", None));
        ___qtreewidgetitem2.setText(2, QCoreApplication.translate("Widget", u"Dispositivo", None));
        ___qtreewidgetitem2.setText(1, QCoreApplication.translate("Widget", u"Canal", None));
        ___qtreewidgetitem2.setText(0, QCoreApplication.translate("Widget", u"Nombre", None));
        ___qtreewidgetitem3 = self.dispositivos_dispositivos_conectados.headerItem()
        ___qtreewidgetitem3.setText(3, QCoreApplication.translate("Widget", u"Conexion", None));
        ___qtreewidgetitem3.setText(2, QCoreApplication.translate("Widget", u"Canales", None));
        ___qtreewidgetitem3.setText(1, QCoreApplication.translate("Widget", u"Modelo", None));
        ___qtreewidgetitem3.setText(0, QCoreApplication.translate("Widget", u"id", None));
        ___qtreewidgetitem4 = self.dispositivos_dispositivos_disponibles.headerItem()
        ___qtreewidgetitem4.setText(0, QCoreApplication.translate("Widget", u"id", None));
        self.status_2.setText("")
        self.dispositivos_guardar_perfil.setText(QCoreApplication.translate("Widget", u"Guardar Perfil Canales", None))
        self.dispositivos_cargar_perfil.setText(QCoreApplication.translate("Widget", u"Cargar Perfil Canales", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Widget", u"Osciloscopios", None))
        self.adquisicion_label_archivos_locales.setText("")
        self.label_8.setText(QCoreApplication.translate("Widget", u"Preview", None))
        self.adquisicion_seleccionar_carpeta.setText(QCoreApplication.translate("Widget", u"Cambiar Carpeta Local", None))
        self.adquisicion_auto.setText(QCoreApplication.translate("Widget", u"Auto Adquirir", None))
        self.adquisicion_adquirir.setText(QCoreApplication.translate("Widget", u"Adquirir", None))
        self.adquisicion_auto_imagenes.setText(QCoreApplication.translate("Widget", u"Ingresar Archivos Nuevos", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"Carpeta Origen Seleccionada:", None))
        self.adquisicion_seleccionar_carpeta_imagenes.setText(QCoreApplication.translate("Widget", u"Seleccionar Carpeta", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"Fuente de Trigger", None))
        self.adquisicion_guardar.setText(QCoreApplication.translate("Widget", u"Guardar", None))
        self.label_22.setText(QCoreApplication.translate("Widget", u"Carpeta Local", None))
        ___qtreewidgetitem5 = self.adquisicion_archivos_locales.headerItem()
        ___qtreewidgetitem5.setText(1, QCoreApplication.translate("Widget", u"Filename", None));
        ___qtreewidgetitem5.setText(0, QCoreApplication.translate("Widget", u"Datapoint", None));
        self.label_10.setText(QCoreApplication.translate("Widget", u"Canales", None))
        self.adquisicion_refrescar.setText(QCoreApplication.translate("Widget", u"Refrescar", None))
        self.adquisicion_auto_guardar.setText(QCoreApplication.translate("Widget", u"Auto Guardar", None))
        self.adquisicion_label_carpeta_imagenes.setText("")
        ___qtreewidgetitem6 = self.adquisicion_origen_datos.headerItem()
        ___qtreewidgetitem6.setText(2, QCoreApplication.translate("Widget", u"Dispositivo", None));
        ___qtreewidgetitem6.setText(1, QCoreApplication.translate("Widget", u"Canal", None));
        ___qtreewidgetitem6.setText(0, QCoreApplication.translate("Widget", u"Nombre", None));
        self.adquisicion_label_preview.setText("")
        self.adquisicion_preview_image.setText("")
        self.adquisicion_preview_text.setHtml(QCoreApplication.translate("Widget", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_23.setText(QCoreApplication.translate("Widget", u"Prefijo :", None))
        self.adquisicion_prefijo.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Widget", u"Adquisicion", None))
        self.bd_seleccionar_carpeta.setText(QCoreApplication.translate("Widget", u"Cambiar Carpeta Local", None))
        self.bd_subir.setText(QCoreApplication.translate("Widget", u"Subir Datos", None))
        self.bd_label_archivos_locales.setText("")
        self.label_3.setText(QCoreApplication.translate("Widget", u"Experimento", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"Jornada", None))
        self.bd_experimento.setItemText(0, QCoreApplication.translate("Widget", u"PF2J - Desgaste", None))

        self.bd_jornada.setItemText(0, QCoreApplication.translate("Widget", u"25 Enero", None))
        self.bd_jornada.setItemText(1, QCoreApplication.translate("Widget", u"27 Abril", None))
        self.bd_jornada.setItemText(2, QCoreApplication.translate("Widget", u"03 Mayo", None))

        self.bd_agregar_experimento.setText(QCoreApplication.translate("Widget", u"+", None))
        self.bd_agregar_jornada.setText(QCoreApplication.translate("Widget", u"+", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"Usuario", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"Archivos Servidor", None))
        ___qtreewidgetitem7 = self.bd_archivos_servidor.headerItem()
        ___qtreewidgetitem7.setText(1, QCoreApplication.translate("Widget", u"Filename", None));
        ___qtreewidgetitem7.setText(0, QCoreApplication.translate("Widget", u"Datapoint", None));
        ___qtreewidgetitem8 = self.bd_archivos_locales.headerItem()
        ___qtreewidgetitem8.setText(3, QCoreApplication.translate("Widget", u"Subir", None));
        ___qtreewidgetitem8.setText(2, QCoreApplication.translate("Widget", u"En Servidor", None));
        ___qtreewidgetitem8.setText(1, QCoreApplication.translate("Widget", u"Filename", None));
        ___qtreewidgetitem8.setText(0, QCoreApplication.translate("Widget", u"Datapoint", None));
        self.label_15.setText(QCoreApplication.translate("Widget", u"Contrase\u00f1a", None))
        self.label_16.setText(QCoreApplication.translate("Widget", u"IP Servidor", None))
        self.bd_refrescar.setText(QCoreApplication.translate("Widget", u"Refrescar Carpeta Local", None))
        self.label_18.setText(QCoreApplication.translate("Widget", u"Descripcion", None))
        ___qtreewidgetitem9 = self.bd_parametros_locales.headerItem()
        ___qtreewidgetitem9.setText(4, QCoreApplication.translate("Widget", u"Subir", None));
        ___qtreewidgetitem9.setText(3, QCoreApplication.translate("Widget", u"Unidad", None));
        ___qtreewidgetitem9.setText(2, QCoreApplication.translate("Widget", u"Valor", None));
        ___qtreewidgetitem9.setText(1, QCoreApplication.translate("Widget", u"Par\u00e1metro", None));
        ___qtreewidgetitem9.setText(0, QCoreApplication.translate("Widget", u"Datapoint", None));
        self.label_20.setText(QCoreApplication.translate("Widget", u"Parametros Locales", None))
        self.label_21.setText(QCoreApplication.translate("Widget", u"Archivos Locales", None))
        self.bd_descripcion.setHtml(QCoreApplication.translate("Widget", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.bd_refrescar_servidor.setText(QCoreApplication.translate("Widget", u"Conectar / Refrescar Servidor", None))
        self.label_24.setText(QCoreApplication.translate("Widget", u"Parametros Servidor", None))
        ___qtreewidgetitem10 = self.bd_parametros_servidor.headerItem()
        ___qtreewidgetitem10.setText(3, QCoreApplication.translate("Widget", u"Unidad", None));
        ___qtreewidgetitem10.setText(2, QCoreApplication.translate("Widget", u"Valor", None));
        ___qtreewidgetitem10.setText(1, QCoreApplication.translate("Widget", u"Par\u00e1metro", None));
        ___qtreewidgetitem10.setText(0, QCoreApplication.translate("Widget", u"Datapoint", None));
        self.bd_usuario.setText("")
        self.bd_password.setText("")
        self.bd_ip.setText(QCoreApplication.translate("Widget", u"200.28.103.190", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Widget", u"Base de Datos", None))
        self.log.setHtml(QCoreApplication.translate("Widget", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_92.setText(QCoreApplication.translate("Widget", u"Registro de Eventos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("Widget", u"Registro", None))
        self.status.setText(QCoreApplication.translate("Widget", u"Status: OK", None))
    # retranslateUi

