# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\agregarExperimento.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgregarExperimento(object):
    def setupUi(self, AgregarExperimento):
        AgregarExperimento.setObjectName("AgregarExperimento")
        AgregarExperimento.resize(353, 301)
        self.cancelar = QtWidgets.QPushButton(AgregarExperimento)
        self.cancelar.setGeometry(QtCore.QRect(210, 230, 101, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelar.setFont(font)
        self.cancelar.setObjectName("cancelar")
        self.agregar = QtWidgets.QPushButton(AgregarExperimento)
        self.agregar.setGeometry(QtCore.QRect(50, 230, 91, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.agregar.setFont(font)
        self.agregar.setObjectName("agregar")
        self.label_2 = QtWidgets.QLabel(AgregarExperimento)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 151, 20))
        self.label_2.setObjectName("label_2")
        self.label_91 = QtWidgets.QLabel(AgregarExperimento)
        self.label_91.setGeometry(QtCore.QRect(30, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.nombre = QtWidgets.QLineEdit(AgregarExperimento)
        self.nombre.setGeometry(QtCore.QRect(190, 90, 121, 21))
        self.nombre.setText("")
        self.nombre.setObjectName("nombre")
        self.label = QtWidgets.QLabel(AgregarExperimento)
        self.label.setGeometry(QtCore.QRect(50, 140, 261, 51))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(AgregarExperimento)
        QtCore.QMetaObject.connectSlotsByName(AgregarExperimento)

    def retranslateUi(self, AgregarExperimento):
        _translate = QtCore.QCoreApplication.translate
        AgregarExperimento.setWindowTitle(_translate("AgregarExperimento", "Dialog"))
        self.cancelar.setText(_translate("AgregarExperimento", "Cancelar"))
        self.agregar.setText(_translate("AgregarExperimento", "Agregar"))
        self.label_2.setText(_translate("AgregarExperimento", "Nombre"))
        self.label_91.setText(_translate("AgregarExperimento", "Agregar Experimento"))
        self.label.setText(_translate("AgregarExperimento", "Nota: Esto agregara el nuevo experimento al servidor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgregarExperimento = QtWidgets.QDialog()
    ui = Ui_AgregarExperimento()
    ui.setupUi(AgregarExperimento)
    AgregarExperimento.show()
    sys.exit(app.exec_())
