# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dispositivoIp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DispositivoIp(object):
    def setupUi(self, DispositivoIp):
        DispositivoIp.setObjectName("DispositivoIp")
        DispositivoIp.resize(381, 213)
        self.cancelar = QtWidgets.QPushButton(DispositivoIp)
        self.cancelar.setGeometry(QtCore.QRect(222, 150, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelar.setFont(font)
        self.cancelar.setObjectName("cancelar")
        self.conectar = QtWidgets.QPushButton(DispositivoIp)
        self.conectar.setGeometry(QtCore.QRect(50, 150, 101, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.conectar.setFont(font)
        self.conectar.setObjectName("conectar")
        self.label_2 = QtWidgets.QLabel(DispositivoIp)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 121, 20))
        self.label_2.setObjectName("label_2")
        self.label_91 = QtWidgets.QLabel(DispositivoIp)
        self.label_91.setGeometry(QtCore.QRect(30, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.ip = QtWidgets.QLineEdit(DispositivoIp)
        self.ip.setGeometry(QtCore.QRect(210, 90, 121, 21))
        self.ip.setText("")
        self.ip.setObjectName("ip")

        self.retranslateUi(DispositivoIp)
        QtCore.QMetaObject.connectSlotsByName(DispositivoIp)

    def retranslateUi(self, DispositivoIp):
        _translate = QtCore.QCoreApplication.translate
        DispositivoIp.setWindowTitle(_translate("DispositivoIp", "Dialog"))
        self.cancelar.setText(_translate("DispositivoIp", "Cancelar"))
        self.conectar.setText(_translate("DispositivoIp", "Conectar"))
        self.label_2.setText(_translate("DispositivoIp", "IP"))
        self.label_91.setText(_translate("DispositivoIp", "Conectar Osciloscopio en LAN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DispositivoIp = QtWidgets.QDialog()
    ui = Ui_DispositivoIp()
    ui.setupUi(DispositivoIp)
    DispositivoIp.show()
    sys.exit(app.exec_())
