# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\eliminarArchivo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EliminarArchivo(object):
    def setupUi(self, EliminarArchivo):
        EliminarArchivo.setObjectName("EliminarArchivo")
        EliminarArchivo.resize(733, 529)
        self.cancelar = QtWidgets.QPushButton(EliminarArchivo)
        self.cancelar.setGeometry(QtCore.QRect(450, 470, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelar.setFont(font)
        self.cancelar.setObjectName("cancelar")
        self.eliminar = QtWidgets.QPushButton(EliminarArchivo)
        self.eliminar.setGeometry(QtCore.QRect(172, 470, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.eliminar.setFont(font)
        self.eliminar.setObjectName("eliminar")
        self.archivo = QtWidgets.QLabel(EliminarArchivo)
        self.archivo.setGeometry(QtCore.QRect(80, 120, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.archivo.setFont(font)
        self.archivo.setText("")
        self.archivo.setAlignment(QtCore.Qt.AlignCenter)
        self.archivo.setWordWrap(True)
        self.archivo.setObjectName("archivo")
        self.frame = QtWidgets.QFrame(EliminarArchivo)
        self.frame.setGeometry(QtCore.QRect(80, 180, 591, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.preview_image = QtWidgets.QLabel(self.frame)
        self.preview_image.setGeometry(QtCore.QRect(0, 0, 591, 261))
        self.preview_image.setText("")
        self.preview_image.setAlignment(QtCore.Qt.AlignCenter)
        self.preview_image.setObjectName("preview_image")
        self.preview_text = QtWidgets.QTextBrowser(self.frame)
        self.preview_text.setGeometry(QtCore.QRect(0, 0, 591, 261))
        self.preview_text.setObjectName("preview_text")
        self.preview_graph = PlotWidget(self.frame)
        self.preview_graph.setGeometry(QtCore.QRect(0, 0, 591, 261))
        self.preview_graph.setAutoFillBackground(False)
        self.preview_graph.setObjectName("preview_graph")
        self.label_91 = QtWidgets.QLabel(EliminarArchivo)
        self.label_91.setGeometry(QtCore.QRect(190, 30, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setWordWrap(True)
        self.label_91.setObjectName("label_91")

        self.retranslateUi(EliminarArchivo)
        QtCore.QMetaObject.connectSlotsByName(EliminarArchivo)

    def retranslateUi(self, EliminarArchivo):
        _translate = QtCore.QCoreApplication.translate
        EliminarArchivo.setWindowTitle(_translate("EliminarArchivo", "Dialog"))
        self.cancelar.setText(_translate("EliminarArchivo", "Cancelar"))
        self.eliminar.setText(_translate("EliminarArchivo", "Eliminar"))
        self.preview_text.setHtml(_translate("EliminarArchivo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_91.setText(_translate("EliminarArchivo", "¿Eliminar este archivo?"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EliminarArchivo = QtWidgets.QDialog()
    ui = Ui_EliminarArchivo()
    ui.setupUi(EliminarArchivo)
    EliminarArchivo.show()
    sys.exit(app.exec_())
