# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\asignarDatapoint.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AsignarDatapoint(object):
    def setupUi(self, AsignarDatapoint):
        AsignarDatapoint.setObjectName("AsignarDatapoint")
        AsignarDatapoint.resize(733, 529)
        self.cancelar = QtWidgets.QPushButton(AsignarDatapoint)
        self.cancelar.setGeometry(QtCore.QRect(450, 470, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelar.setFont(font)
        self.cancelar.setObjectName("cancelar")
        self.asignar = QtWidgets.QPushButton(AsignarDatapoint)
        self.asignar.setGeometry(QtCore.QRect(170, 470, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.asignar.setFont(font)
        self.asignar.setObjectName("asignar")
        self.label_2 = QtWidgets.QLabel(AsignarDatapoint)
        self.label_2.setGeometry(QtCore.QRect(230, 420, 151, 20))
        self.label_2.setObjectName("label_2")
        self.label_91 = QtWidgets.QLabel(AsignarDatapoint)
        self.label_91.setGeometry(QtCore.QRect(220, 10, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.frame = QtWidgets.QFrame(AsignarDatapoint)
        self.frame.setGeometry(QtCore.QRect(80, 130, 591, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.preview_text = QtWidgets.QTextBrowser(self.frame)
        self.preview_text.setGeometry(QtCore.QRect(0, 0, 591, 261))
        self.preview_text.setObjectName("preview_text")
        self.preview_image = QtWidgets.QLabel(self.frame)
        self.preview_image.setGeometry(QtCore.QRect(0, 0, 591, 261))
        self.preview_image.setText("")
        self.preview_image.setAlignment(QtCore.Qt.AlignCenter)
        self.preview_image.setObjectName("preview_image")
        self.preview_graph = PlotWidget(self.frame)
        self.preview_graph.setGeometry(QtCore.QRect(0, 0, 591, 261))
        self.preview_graph.setAutoFillBackground(False)
        self.preview_graph.setObjectName("preview_graph")
        self.archivo = QtWidgets.QLabel(AsignarDatapoint)
        self.archivo.setGeometry(QtCore.QRect(90, 70, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.archivo.setFont(font)
        self.archivo.setText("")
        self.archivo.setAlignment(QtCore.Qt.AlignCenter)
        self.archivo.setWordWrap(True)
        self.archivo.setObjectName("archivo")
        self.datapoint = QtWidgets.QLineEdit(AsignarDatapoint)
        self.datapoint.setGeometry(QtCore.QRect(380, 420, 121, 21))
        self.datapoint.setText("")
        self.datapoint.setObjectName("datapoint")

        self.retranslateUi(AsignarDatapoint)
        QtCore.QMetaObject.connectSlotsByName(AsignarDatapoint)

    def retranslateUi(self, AsignarDatapoint):
        _translate = QtCore.QCoreApplication.translate
        AsignarDatapoint.setWindowTitle(_translate("AsignarDatapoint", "Dialog"))
        self.cancelar.setText(_translate("AsignarDatapoint", "Cancelar"))
        self.asignar.setText(_translate("AsignarDatapoint", "Asignar"))
        self.label_2.setText(_translate("AsignarDatapoint", "Datapont"))
        self.label_91.setText(_translate("AsignarDatapoint", "Asignar Datapoint"))
        self.preview_text.setHtml(_translate("AsignarDatapoint", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AsignarDatapoint = QtWidgets.QDialog()
    ui = Ui_AsignarDatapoint()
    ui.setupUi(AsignarDatapoint)
    AsignarDatapoint.show()
    sys.exit(app.exec_())
