# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\desconectarDispositivo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DesconectarDispositivo(object):
    def setupUi(self, DesconectarDispositivo):
        DesconectarDispositivo.setObjectName("DesconectarDispositivo")
        DesconectarDispositivo.resize(450, 305)
        self.cancelar = QtWidgets.QPushButton(DesconectarDispositivo)
        self.cancelar.setGeometry(QtCore.QRect(272, 250, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelar.setFont(font)
        self.cancelar.setObjectName("cancelar")
        self.desconectar = QtWidgets.QPushButton(DesconectarDispositivo)
        self.desconectar.setGeometry(QtCore.QRect(70, 250, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.desconectar.setFont(font)
        self.desconectar.setObjectName("desconectar")
        self.dispositivo = QtWidgets.QLabel(DesconectarDispositivo)
        self.dispositivo.setGeometry(QtCore.QRect(70, 150, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dispositivo.setFont(font)
        self.dispositivo.setText("")
        self.dispositivo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dispositivo.setObjectName("dispositivo")
        self.label_91 = QtWidgets.QLabel(DesconectarDispositivo)
        self.label_91.setGeometry(QtCore.QRect(60, 40, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setWordWrap(True)
        self.label_91.setObjectName("label_91")

        self.retranslateUi(DesconectarDispositivo)
        QtCore.QMetaObject.connectSlotsByName(DesconectarDispositivo)

    def retranslateUi(self, DesconectarDispositivo):
        _translate = QtCore.QCoreApplication.translate
        DesconectarDispositivo.setWindowTitle(_translate("DesconectarDispositivo", "Dialog"))
        self.cancelar.setText(_translate("DesconectarDispositivo", "Cancelar"))
        self.desconectar.setText(_translate("DesconectarDispositivo", "Desconectar"))
        self.label_91.setText(_translate("DesconectarDispositivo", "¿Desconectar este dispositivo?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DesconectarDispositivo = QtWidgets.QDialog()
    ui = Ui_DesconectarDispositivo()
    ui.setupUi(DesconectarDispositivo)
    DesconectarDispositivo.show()
    sys.exit(app.exec_())
