# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\guardarDescripcion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GuardarDescripcion(object):
    def setupUi(self, GuardarDescripcion):
        GuardarDescripcion.setObjectName("GuardarDescripcion")
        GuardarDescripcion.resize(365, 220)
        self.cancelar = QtWidgets.QPushButton(GuardarDescripcion)
        self.cancelar.setGeometry(QtCore.QRect(220, 130, 83, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelar.setFont(font)
        self.cancelar.setObjectName("cancelar")
        self.si = QtWidgets.QPushButton(GuardarDescripcion)
        self.si.setGeometry(QtCore.QRect(70, 130, 83, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.si.setFont(font)
        self.si.setObjectName("si")
        self.label_91 = QtWidgets.QLabel(GuardarDescripcion)
        self.label_91.setGeometry(QtCore.QRect(10, 40, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setWordWrap(True)
        self.label_91.setObjectName("label_91")

        self.retranslateUi(GuardarDescripcion)
        QtCore.QMetaObject.connectSlotsByName(GuardarDescripcion)

    def retranslateUi(self, GuardarDescripcion):
        _translate = QtCore.QCoreApplication.translate
        GuardarDescripcion.setWindowTitle(_translate("GuardarDescripcion", "Dialog"))
        self.cancelar.setText(_translate("GuardarDescripcion", "Cancelar"))
        self.si.setText(_translate("GuardarDescripcion", "Si"))
        self.label_91.setText(_translate("GuardarDescripcion", "¿Guardar Descripcion?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GuardarDescripcion = QtWidgets.QDialog()
    ui = Ui_GuardarDescripcion()
    ui.setupUi(GuardarDescripcion)
    GuardarDescripcion.show()
    sys.exit(app.exec_())
