# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\subirBd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Subir(object):
    def setupUi(self, Subir):
        Subir.setObjectName("Subir")
        Subir.resize(381, 249)
        self.cancelar = QtWidgets.QPushButton(Subir)
        self.cancelar.setGeometry(QtCore.QRect(240, 190, 121, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelar.setFont(font)
        self.cancelar.setObjectName("cancelar")
        self.subir = QtWidgets.QPushButton(Subir)
        self.subir.setGeometry(QtCore.QRect(20, 190, 121, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subir.setFont(font)
        self.subir.setObjectName("subir")
        self.label_91 = QtWidgets.QLabel(Subir)
        self.label_91.setGeometry(QtCore.QRect(20, 30, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setWordWrap(True)
        self.label_91.setObjectName("label_91")
        self.label = QtWidgets.QLabel(Subir)
        self.label.setGeometry(QtCore.QRect(40, 120, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Subir)
        QtCore.QMetaObject.connectSlotsByName(Subir)

    def retranslateUi(self, Subir):
        _translate = QtCore.QCoreApplication.translate
        Subir.setWindowTitle(_translate("Subir", "Dialog"))
        self.cancelar.setText(_translate("Subir", "Cancelar"))
        self.subir.setText(_translate("Subir", "Subir"))
        self.label_91.setText(_translate("Subir", "¿Subir los datos seleccionados al servidor?"))
        self.label.setText(_translate("Subir", "Algunos datos podrian sobreescribirse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Subir = QtWidgets.QDialog()
    ui = Ui_Subir()
    ui.setupUi(Subir)
    Subir.show()
    sys.exit(app.exec_())
