# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\agregarFiltro.ui'
#
# Created by: PySide6 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyside6-uic is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_AgregarFiltro(object):
    def setupUi(self, AgregarFiltro):
        AgregarFiltro.setObjectName("AgregarFiltro")
        AgregarFiltro.resize(381, 341)
        self.cancelar = QtWidgets.QPushButton(AgregarFiltro)
        self.cancelar.setGeometry(QtCore.QRect(220, 280, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelar.setFont(font)
        self.cancelar.setObjectName("cancelar")
        self.agregar = QtWidgets.QPushButton(AgregarFiltro)
        self.agregar.setGeometry(QtCore.QRect(60, 280, 101, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.agregar.setFont(font)
        self.agregar.setObjectName("agregar")
        self.label = QtWidgets.QLabel(AgregarFiltro)
        self.label.setGeometry(QtCore.QRect(60, 150, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.condicion = QtWidgets.QComboBox(AgregarFiltro)
        self.condicion.setGeometry(QtCore.QRect(190, 150, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.condicion.setFont(font)
        self.condicion.setObjectName("condicion")
        self.label_2 = QtWidgets.QLabel(AgregarFiltro)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AgregarFiltro)
        self.label_3.setGeometry(QtCore.QRect(60, 210, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.parametro = QtWidgets.QComboBox(AgregarFiltro)
        self.parametro.setGeometry(QtCore.QRect(190, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.parametro.setFont(font)
        self.parametro.setObjectName("parametro")
        self.label_91 = QtWidgets.QLabel(AgregarFiltro)
        self.label_91.setGeometry(QtCore.QRect(30, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.valor = QtWidgets.QLineEdit(AgregarFiltro)
        self.valor.setGeometry(QtCore.QRect(190, 210, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.valor.setFont(font)
        self.valor.setText("")
        self.valor.setObjectName("valor")

        self.retranslateUi(AgregarFiltro)
        QtCore.QMetaObject.connectSlotsByName(AgregarFiltro)

    def retranslateUi(self, AgregarFiltro):
        _translate = QtCore.QCoreApplication.translate
        AgregarFiltro.setWindowTitle(_translate("AgregarFiltro", "Dialog"))
        self.cancelar.setText(_translate("AgregarFiltro", "Cancelar"))
        self.agregar.setText(_translate("AgregarFiltro", "Agregar"))
        self.label.setText(_translate("AgregarFiltro", "Condicion"))
        self.label_2.setText(_translate("AgregarFiltro", "Parametro"))
        self.label_3.setText(_translate("AgregarFiltro", "Valor"))
        self.label_91.setText(_translate("AgregarFiltro", "Agregar Filtro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgregarFiltro = QtWidgets.QDialog()
    ui = Ui_AgregarFiltro()
    ui.setupUi(AgregarFiltro)
    AgregarFiltro.show()
    sys.exit(app.exec())
